packages:
  - 'apps/*'
  - 'packages/*'
catalogs:
  prisma:
    prisma: latest
allowBuilds:
  '@discordjs/opus': true
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  ffmpeg-static: true
  prisma: true
  sharp: true
minimumReleaseAgeExclude:
  - '@eslint/plugin-kit@0.7.2'
  - eslint@10.4.1
